[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true

[tool.mypy-src.*]
allow_untyped_calls = true
allow_any_generics = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]

