/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7IIwirrf/NZmfNgdezVcnHw19So7t65dqLVKCtKjadR0bErfdLa1JM2vdDEn3LMej6yySMmsyYJBVbKoX0ZBOg==
 */

/* eslint-disable */
// tslint:disable

import FlywaySchemaHistory, {FlywaySchemaHistory_InsertParameters} from './flyway_schema_history'
import Settlements, {Settlements_InsertParameters} from './settlements'

interface DatabaseSchema {
  flyway_schema_history: {record: FlywaySchemaHistory, insert: FlywaySchemaHistory_InsertParameters};
  settlements: {record: Settlements, insert: Settlements_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  FlywaySchemaHistory,
  FlywaySchemaHistory_InsertParameters,
  Settlements,
  Settlements_InsertParameters,
}
