/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: E8BU00UcFbMKYI365di+ZAXRXlMspb38qSN4ofMxGu3taDhpdxSDPq4Wio00BOmaH1cnSb+FS2jefVtxmSEfBg==
 */

/* eslint-disable */
// tslint:disable

interface InternalizedImbalances {
  amount: string | null;
  token: Buffer & { readonly __brand?: "internalized_imbalances_token" };
  tx_hash: Buffer & { readonly __brand?: "internalized_imbalances_tx_hash" };
}
export default InternalizedImbalances;

interface InternalizedImbalances_InsertParameters {
  amount?: string | null;
  token: Buffer & { readonly __brand?: "internalized_imbalances_token" };
  tx_hash: Buffer & { readonly __brand?: "internalized_imbalances_tx_hash" };
}
export type { InternalizedImbalances_InsertParameters };
