/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LYIa5eyMbviNvndGFxojREFi7BV4A6l9O60ryWwDolNSS9OM2seRjIdFVAW52hNs+yP8reK6zRAdfpcaIPHGfw==
 */

/* eslint-disable */
// tslint:disable

interface Settlements {
  block_number: number & { readonly __brand?: "settlements_block_number" };
  log_index: number & { readonly __brand?: "settlements_log_index" };
  solver: Buffer;
  tx_hash: Buffer;
}
export default Settlements;

interface Settlements_InsertParameters {
  block_number: number & { readonly __brand?: "settlements_block_number" };
  log_index: number & { readonly __brand?: "settlements_log_index" };
  solver: Buffer;
  tx_hash: Buffer;
}
export type { Settlements_InsertParameters };
